repos:
  - repo: local
    hooks:
      - id: run-changed-tests
        name: Run tests for changed directories
        entry: ./scripts/run_changed_tests.sh
        language: script
        pass_filenames: false

