FILLER_PREFIXES = (
    'thank you',
    'thanks',
    'yeah',
    'yes',
    'good morning',
    'great',
    'ok',
    'hi',
    'okay',
    'sure',
    'got it',
    'all right',
    'thank you very much',
    'hey',
    'good morning, everyone',
    'next question, please',
    'thanks for the question',
    'thanks for taking my question',
    'thanks so much',
    'right',
    'thanks very much',
    'no',
    'thanks for taking the question',
    "that's helpful",
    'hi, good morning',
    'good afternoon',
    'good morning, guys',
    'next question please',
    'thanks for taking my questions',
    'hey, good morning',
    'hey, guys',
    'thank you so much',
    'next question',
    'thanks, guys',
)
